### ISSUE TITLE
Deploy server to debug.getferdi.com

### ISSUE THREAD

**Issue by kytwb** [getferdi/debugger#1]

**Comment by vantezzen** [comment]
I guess we let this run on the same EC2 instance as the API? In that case you'll have to add a DNS record to Cloudflare and we'll have to setup a new config for the Ngnix reverse proxy. I'd also suggest that we use a local sqlite database for this as the saved information is not that important.

**Comment by kytwb** [comment]
Added the DNS entry for `debug` to point to 18.136.123.39.

**Comment by vantezzen** [comment]
Ok, I just setup the debugger on the server and will now add the config for Ngnix and will notify you before activating it so you can verify it, ok?

**Comment by vantezzen** [comment]
Ok, I now added the configuration for the ngnix debugger reverse proxy to `/etc/nginx/sites-available/debugger` and created a symbolic link to `sites-enabled`. I had to change the original config as well as it had listened on all domains instead of just `api.getferdi.com`. `ngnix -t` is successful.
Can you look over these config files too as I am not too experienced with Ngnix configurations?

**Comment by vantezzen** [comment]
Ok, restarted Ngnix now and the debugger is up and running

**Comment by kytwb** [comment]
@vantezzen thanks for taking care of it, still not fully operational over here; hopefully getting stable internet back soon.
